[package]
name = "kdnsq"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hickory-proto = "0.24.0"
hickory-resolver = "0.24.0"
tokio = { version = "1.34.0", features = ["full"] }
